//! Shared domain and session-lifecycle code for agtk.

pub mod agent_hooks;
pub mod agent_status;
pub mod appearance;
pub mod azure;
pub mod capture;
pub mod changes;
pub mod claude_presets;
pub mod command_runner;
pub mod control;
pub mod emacs;
pub mod explorer;
pub mod file_links;
pub mod history;
pub mod instance;
pub mod io_worker;
pub mod launch_model;
pub mod launch_preferences;
pub mod mcp;
pub mod persist;
pub mod projects;
pub mod providers;
pub mod session;
mod session_names;
pub mod shortcuts;
pub mod terminal_text;
pub mod ui;
pub mod welcome;
pub mod workspace_tabs;
pub mod worktrees;
